/*
 * This source file was generated by the Gradle 'init' task
 */
package web_scraper;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
